<?php

namespace MapBundle\Repository;

/**
 * OverlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OverlayRepository extends \Doctrine\ORM\EntityRepository
{
}
